# Generated by Django 3.2.7 on 2021-10-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=200, unique=True)),
                ('categoria', models.TextField(max_length=100)),
                ('qtd', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
