# Generated by Django 3.2.7 on 2021-09-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=200)),
                ('categoria', models.TextField(max_length=100)),
                ('qtd', models.IntegerField(default=1)),
            ],
        ),
    ]
