# Generated by Django 3.2.7 on 2021-09-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField(max_length=600)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacktypemodel')),
            ],
        ),
    ]
