# Generated by Django 3.2.7 on 2021-09-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='nome_legal',
            field=models.TextField(default='a', max_length=100),
        ),
    ]
