# Generated by Django 3.2.7 on 2021-11-17 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedbackmodel_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typee', to='feedback.feedbacktypemodel'),
        ),
    ]
