# Generated by Django 3.2.7 on 2021-10-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_feedbackmodel_nome_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacktypemodel'),
        ),
    ]
