# Generated by Django 3.2.7 on 2021-10-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedbackmodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='type',
            field=models.ManyToManyField(to='feedback.FeedbackTypeModel'),
        ),
    ]
