# Generated by Django 3.2.7 on 2021-10-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20211008_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacktypemodel'),
            preserve_default=False,
        ),
    ]
