# Generated by Django 3.2.7 on 2021-10-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20211008_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacktypemodel'),
        ),
    ]
